In [1]:
import numpy as np
import cv2

In [3]:
%pip install opencv-python



     --------------------------------------- 38.2/38.2 MB 26.2 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [6]:
import cv2
testVideoPath: str = "test-video.mp4"
videoCapture = cv2.VideoCapture(testVideoPath)

print (videoCapture.isOpened())   # True = read video successfully. False - fail to read video.

fourcc = cv2.VideoWriter_fourcc(*'XVID')

videoWriter = cv2.VideoWriter("output_video.avi", fourcc, 20.0, (640, 360))

print (videoWriter.isOpened())  # True = write out video successfully. False - fail to write out video.

videoCapture.release()

videoWriter.release()

True
True


In [9]:
classifierPath:str = 'haarcascade_frontalface_default.xml';
face_cascade = cv2.CascadeClassifier(classifierPath)

In [11]:
classifierPath:str = 'haarcascade_frontalface_default.xml';
face_cascade = cv2.CascadeClassifier(classifierPath)

cap = cv2.VideoCapture(0)
id = input('enter user id')
sampleN=0;
while 1:
    ret, img = cap.read()
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    faces = face_cascade.detectMultiScale(gray, 1.3, 5)
    for (x,y,w,h) in faces:
        sampleN=sampleN+1;
        cv2.imwrite("F:/Program Files/projects/face_rec/facesData/User."+str(id)+ "." +str(sampleN)+ ".jpg", gray[y:y+h, x:x+w])
        cv2.rectangle(img,(x,y),(x+w,y+h),(255,0,0),2)
        cv2.waitKey(100)
    cv2.imshow('img',img)
    cv2.waitKey(1)
    if sampleN > 20:
        break

cap.release()
cv2.destroyAllWindows()

enter user id1


error: OpenCV(4.7.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'


In [2]:
import cv2
import sys

# Get user supplied values
imagePath = "abba.png"# sys.argv[1]
cascPath = "haarcascade_frontalface_default.xml"

# Create the haar cascade
cascadeClassifier = cv2.CascadeClassifier(cascPath)

# Read the image
image = cv2.imread(imagePath)
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

# Detect faces in the image
faces = cascadeClassifier.detectMultiScale(
    gray,
    scaleFactor=1.1,
    minNeighbors=5,
    minSize=(30, 30),
    flags = cv2.CASCADE_SCALE_IMAGE
)

print(faces)

print("Found {0} faces!".format(len(faces)))

# Draw a rectangle around the faces
for (x, y, w, h) in faces:
    cv2.rectangle(image, (x, y), (x+w, y+h), (0, 255, 0), 2)

print(cv2.imshow("Faces found", image))

[[ 56  55  75  75]
 [168  70  66  66]
 [267  69  87  87]
 [354  78  74  74]]
Found 4 faces!
None
